# Generated by Django 4.2.7 on 2024-01-02 08:21

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Member',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('input1', models.CharField(max_length=100)),
                ('input2', models.CharField(max_length=100)),
                ('input3', models.CharField(max_length=100)),
            ],
        ),
    ]
